
from action_extraction import *



script2=[['Nadeesha', 'remain.'],
 ['Nadeesha', 'So'],
 ['Nilaksha', "it's about a day for"],
 ['Nadeesha',
  "you, including Uniqlo will be 44 million and Lululemon. We have assumed a 5.5 million increase current 25 million. So it will go up to 30 media and other customers. So this is what the CES has committed for the win. 25 current scenario, it's around 35 million. So do all the adjustments have been done from beef, all three scenarios because scenario. So, total revenue is at 177 million to. This is a BPL, any faceplate 133, million from BPL and 44 million from. If you go to our rooms, See we have assumed vs R MC to be at 58% Uniqlo, 74% and all the other. I've read customers, 68% and then Lululemon at 55% and other PPL, customers, 57 cassette."],
 ['Nilaksha', 'So one of the action points would be like you know this is to'],
 ['Nilaksha', 'revisit the overall average'],
 ['Nadeesha', 'over all atoms in each'],
 ['Nilaksha',
  '59 to factor, that is impacting. Our entry for both Sri Lanka and India has only two factors are doing'],
 ['Nilaksha',
  'extremely well on the right of provision and all that again error.'],
 ['Nilaksha',
  'One means there are other charges coming to the p and n on the custom duty'],
 ['Nilaksha', 'Tomica for the custom, do turn on that issue.'],
 ['Nilaksha', 'Is whether those are being'],
 ['Nilaksha', 'considered in this. If obese there to be a strong'],
 ['Nilaksha',
  'governance in India, we know that these are being considered at that portion. Hell is'],
 ['Nilaksha',
  '1.9 million dollars here today. That is a profit and time again. We are MC jahnavi. We just go to'],
 ['Nilaksha',
  "Whiter one. Is that there is a 1.9 million dollars here today and then There's another 400 to 500 thousand dollars on a Style, mix Anna seismic. And still there has to be, if is the size made in a phobia, should be compensated for the project is done"],
 ['Nadeesha','exactly the service actually discusses the, how can we make? Sure we have done the right costing, both India following the'],
  ['Dinali',
  "Nine percent at the customer level. So people are absolutely 57%. And if he 64% all together, 59% Dua and PBT, at the V level will be a loss of ten point eight million. So there won't be any change in the Warhead and we have a 1 million open capacity, but no headcount reduction or plant closures have been factored."],
 ['Madduranga', 'The cardinal'],
 ['Madduranga', 'points, also 306'],
 ['Dinali', 'No, no.'],
 ['Madduranga', 'Before we did this piece and then we pull up Shakti need to'],
 ['Dinali',
  "do that. So there is as historical 23 24 and we put this 152 scenario. That's the only"],
 ['Madduranga',
  'scenario 2025 to scenario full capacity and was like, what? And then then you go to the that capacity this much open losses. This one other option is to be considered in the support from him, but we do get to get the customer focus'],
 ['Dinali', 'first.'],
 ['Madduranga',
  "Now we'll put that last time we did this, we go through natural attrition on closer to the board and ask what they like to do"],
 ['Madduranga', 'it personally.'],
 ['Dinali', 'But yeah, I think that we are looking at'],
 ['Madduranga',
  "that time and all that are looking at 5 million for which even we are not even started casting, exercise for that matter any loss. What can be further in? I'm negotiating with vs for another three million dollars that are discounted price. That is one other second option, right? Right. The option is how can we partner and a short-term basis to partner the capacity for me. So anyways, fourth one is that I think how can we leverage on the body line Center of Excellence for grass can Lululemon and we are pardoned or even grass to come to body line."],
 ['Madduranga', 'Nike.'],
 ['Madduranga',
  'In Europe, the to really do something with all our effort. If you go to license office in India, they are not considered as a country for brass. So we have now different. Oo, the'],
 ['Madduranga',
  "dish. They give the sourcing from the place that they sorry, the counter production, alligator material. So it has to be in the country that's and the capability. I think we can find the material is a key capability of the team mouse over the - Lundy,"],
 ['Madduranga',
  "most even trying to get a person and we were training that person. Don't know, where do they"],
 ['Dinali', 'produce? What is the 26 number Seventeen?'],
 ['Madduranga', 'Ninety one ninety'],
 ['Dinali', 'one ninety seven'],
 ['Madduranga',
  "and nine people. We have to say that can potentially. So let's look at it. Who 22nd Serb. These are 200 million dollar business"],
 ['Madduranga', 'scenarios.'],
 ['Dinali',
  "You know, if they are so okay. You're making losses in India. Yeah, you still plan?"],
 ['Madduranga',
  'No, we discussed know that place has to be restated. The link. Again, the new from, to day'],
 ['Madduranga',
  "two, laughs - we have to do it. Something he can technically be shown by the way, when I was there. So no, I think they are comfortable to look at it. So both you and you need to have a preview and see whether it's possible 1.5 million and that's what I call out. 1.5 million, my operation is not feasible. Then we had to look at a part of me. Yes, or eat a more, any other Export Revenue, customer to come, not because of export the customer, which has a higher learning, so that is neutralized overall. That's what I look at. Eat Em mobs, someone is to coming."],
 ['Dinali', 'So do you want'],
 ['Madduranga',
  "Press enter to now, they're looking at what needs to be done on the in for a pheo for your information, we are trying to. We have some the evidence that we can declare cash is there. But we are giving to the shareholder and shareholder has to give it back to the if you need"],
 ['Madduranga',
  "three Lanka with as a dividend tax form, a others don't have right to"],
 ['Dinali',
  "find a way. You don't need to technically present. If you're expecting us anyway, they expecting our"],
 ['Madduranga',
  'board knows. Layers knows they have an through with the layers. Also want to discuss the the boat Olivia. No, we should not go in for something completely different. But now to budget X Cohen it will you look at, you know, Amazo 2:09 get to a profitability. What needs to be done? So yeah, we start making our three million and offer quranic the any model we can offer.'],
 ['Madduranga',
  "The differential meaningful word Athena such a way that they can take it at a different way. So we got that one is aluminum by the time you're presenting. As it we had done this, had that conversation with"],
 ['Dinali',
  'Christa McAuliffe, with exco-members the nation, how to get this full potential pnl,'],
 ['Madduranga',
  "right? My view, you focus, only India for this particular Contour. Can you do anything? Because I had a full potential about how it's barely India. Affordable and away. I know that's on Sundays. Very comfortable with costing. A statement. I don't know who's going to be tasty value-based. Respite"],
 ['Dinali', 'are going to be asked, but I'],
 ['Madduranga', 'want to be with you.'],
 [8, 'Safety area. We are we can do work with the'],
 ['Madduranga',
  "team. This is compared to this level. This is the this should be the Target in compared to other cluster over standard. This should be the Target and these we are we are so this area we need to improve indebtedness. Then we know there's otherwise after doing looking at whether it is coming to another project turned round of says he is too late and if he can know what are the areas remaining which is not doesn't fall under current turn around or Nothing then from the day one, we can start on on something that that is a real. Then we I can, you know, make an A3 and see when home daily weekly monthly. If you"],
 ['Madduranga',
  'start with the target costing this is more than just to identify opportunities on your does. Not see the target here, you can get it by plant level. You can get it by this level only.'],
 ['Madduranga', 'Yeah. Is this fear'],
 ['Madduranga', 'something, whatever that'],
 ['Madduranga', 'whatever hydrate is here next year? Whatever?'],
 ['Madduranga', "Often on feeling, we're going to get our future"],
 ['Madduranga',
  'proofing. Target based on a month apart. You all know that our ability to in the cats in India for efficiency versus lady? Yes we are. They are they are not comfortable'],
 ['Madduranga',
  'to further our savings so we see lots of opportunities to emotional Vision.'],
 [3, 'Options are there?'],
 ['Madduranga',
  "Yeah, no we're not related to the Target. Step you have me. Yeah, yeah, yeah."],
 ['Madduranga', 'We then determined'],
 [8, 'that are important to'],
 ['Madduranga', 'you'],
 [1, 'but you also be'],
 ['Madduranga', 'analyzed and basically, yeah, yes. I just'],
 ['Madduranga', 'So that is, you know, the overhead.'],
 ['Madduranga', 'Should I really do love'],
 ['Madduranga',
  "these? The clock covers to efficiency. They visit, they will put pressure on us, we support this but it didn't ask"],
 [1, 'for an amazing'],
 ['Madduranga', 'doctor, be disgusted banner and the team'],
 [5, 'will come members introduce the savings. And'],
 [8, 'Going to make history.'],
 [2, "That's the capacity. We are looking at"],
 ['Madduranga', '2026 folding'],
 [4, 'back'],
 ['Madduranga', 'up to 25.'],
 [4, 'Based on that, I will give the headphone'],
 ['Madduranga',
  "2026 the power. So the now it has reduced to 1.81 when it come to this resize. This icy right-sizing one so are we take in 2026? That don't know if uh 26"],
 [4, 'rights'],
 ['Madduranga', 'even Twitter Okay.'],
 [4, 'Meperidine.'],
 [1, "We don't get any"],
 ['Madduranga', "beautifully us and the UK. You don't have any vehicles."],
 ['Madduranga', "possibility, it's come"],
 ['Madduranga', 'to England, he said,'],
 ['Madduranga', 'anything is']
  
  ]

act=[]
def action_point(conversation):
    # Collect only the descriptions (second element of each sub-list)
    descriptions = [desc[1] for desc in conversation]
    
    # Join descriptions into a single paragraph
    output_paragraph = " ".join(descriptions)
    # Call the extraction function (assuming it exists)
    action=extract_action_points(output_paragraph)
    act.append(action)
    print(action)

action_point(script2)